In [2]:
! pip install featuretools

Collecting featuretools
  Downloading featuretools-1.31.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: cloudpickle>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (3.1.2)
Requirement already satisfied: holidays>=0.17 in /usr/local/lib/python3.12/dist-packages (from featuretools) (0.98)
Requirement already satisfied: numpy>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (26.2)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (2.2.2)
Requirement already satisfied: psutil>=5.7.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (5.9.5)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from featuretools) (1.16.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from featuretools) (4.67.3)
Collecting woodwork>=0.28.0 (from featuretools)
  Downloading woodwork-0.31.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from holidays>=0.17->featuretools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->featuretools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->featuretools) (2026.2)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from woodwork>=0.28.0->featuretools) (1.6.1)
Requirement already satisfied: importlib-resources>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from woodwork>=0.28.0->featuretools) (7.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.9.0.post0->holidays>=0.17->featuretools) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->woodwork>=0.28.0->featuretools) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->woodwork>=0.28.0->featuretools) (3.6.0)
Downloading featuretools-1.31.0-py3-none-any.whl (587 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.9/587.9 kB 10.7 MB/s eta 0:00:00
Downloading woodwork-0.31.0-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.2/215.2 kB 17.8 MB/s eta 0:00:00
Installing collected packages: woodwork, featuretools
Successfully installed featuretools-1.31.0 woodwork-0.31.0

In [3]:
### Carga de librerias
import pandas as pd
import featuretools as ft

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [4]:
### Cargamos  el data set
data = ft.demo.load_mock_customer()

In [5]:
## Podemos ver que es un diccionario de tablas
print(data['customers'])
print(data['products'])
print(data['sessions'])
print(data['transactions'])

   customer_id zip_code           join_date   birthday
0            1    60091 2011-04-17 10:48:33 1994-07-18
1            2    13244 2012-04-15 23:31:04 1986-08-18
2            3    13244 2011-08-13 15:42:34 2003-11-21
3            4    60091 2011-04-08 20:08:14 2006-08-15
4            5    60091 2010-07-17 05:27:50 1984-07-28
  product_id brand
0          1     B
1          2     B
2          3     B
3          4     B
4          5     A
    session_id  customer_id   device       session_start
0            1            2  desktop 2014-01-01 00:00:00
1            2            5   mobile 2014-01-01 00:17:20
2            3            4   mobile 2014-01-01 00:28:10
3            4            1   mobile 2014-01-01 00:44:25
4            5            4   mobile 2014-01-01 01:11:30
5            6            1   tablet 2014-01-01 01:23:25
6            7            3   tablet 2014-01-01 01:39:40
7            8            4   tablet 2014-01-01 01:55:55
8            9            1  desktop 2014-01-01 02:15:25
9           10            2   tablet 2014-01-01 02:31:40
10          11            4   mobile 2014-01-01 02:47:55
11          12            4  desktop 2014-01-01 03:04:10
12          13            4   mobile 2014-01-01 03:15:00
13          14            1   tablet 2014-01-01 03:28:00
14          15            2  desktop 2014-01-01 03:41:00
15          16            2  desktop 2014-01-01 03:49:40
16          17            2   tablet 2014-01-01 04:00:30
17          18            1  desktop 2014-01-01 04:14:35
18          19            3  desktop 2014-01-01 04:27:35
19          20            5  desktop 2014-01-01 04:46:00
20          21            4  desktop 2014-01-01 05:02:15
21          22            4  desktop 2014-01-01 05:21:45
22          23            3  desktop 2014-01-01 05:32:35
23          24            5   tablet 2014-01-01 05:44:30
24          25            3  desktop 2014-01-01 05:59:40
25          26            1   tablet 2014-01-01 06:17:00
26          27            1   mobile 2014-01-01 06:34:20
27          28            5   mobile 2014-01-01 06:50:35
28          29            1   mobile 2014-01-01 07:10:05
29          30            5  desktop 2014-01-01 07:27:25
30          31            2   mobile 2014-01-01 07:42:35
31          32            5   mobile 2014-01-01 08:02:05
32          33            2   mobile 2014-01-01 08:10:45
33          34            3  desktop 2014-01-01 08:24:50
34          35            3   mobile 2014-01-01 08:44:20
     transaction_id  session_id    transaction_time product_id  amount
0                 2           1 2014-01-01 00:00:00          5  127.64
1               495           1 2014-01-01 00:01:05          2  109.48
2               341           1 2014-01-01 00:02:10          3   95.06
3               308           1 2014-01-01 00:03:15          4   78.92
4               271           1 2014-01-01 00:04:20          3   31.54
..              ...         ...                 ...        ...     ...
495             111          35 2014-01-01 08:56:15          5   55.42
496             203          35 2014-01-01 08:57:20          3   34.87
497             276          35 2014-01-01 08:58:25          1   10.94
498             331          35 2014-01-01 08:59:30          5   19.86
499              37          35 2014-01-01 09:00:35          3  148.31

[500 rows x 5 columns]

In [6]:
## Separamos en cada dataset
df_customers = data["customers"]
df_customers.set_index("customer_id", inplace=True)
df_customers.head()

            zip_code           join_date   birthday
customer_id
1              60091 2011-04-17 10:48:33 1994-07-18
2              13244 2012-04-15 23:31:04 1986-08-18
3              13244 2011-08-13 15:42:34 2003-11-21
4              60091 2011-04-08 20:08:14 2006-08-15
5              60091 2010-07-17 05:27:50 1984-07-28

In [7]:
df_products = data["products"]
df_products.set_index("product_id", inplace=True)
df_products.head()

           brand
product_id
1              B
2              B
3              B
4              B
5              A

In [8]:
df_sessions = data["sessions"]
df_sessions.set_index("session_id", inplace=True)
df_sessions.head()

            customer_id   device       session_start
session_id
1                     2  desktop 2014-01-01 00:00:00
2                     5   mobile 2014-01-01 00:17:20
3                     4   mobile 2014-01-01 00:28:10
4                     1   mobile 2014-01-01 00:44:25
5                     4   mobile 2014-01-01 01:11:30

In [9]:
df_transactions = data["transactions"]
df_transactions.set_index("transaction_id", inplace=True)
df_transactions.head()

                session_id    transaction_time product_id  amount
transaction_id
2                        1 2014-01-01 00:00:00          5  127.64
495                      1 2014-01-01 00:01:05          2  109.48
341                      1 2014-01-01 00:02:10          3   95.06
308                      1 2014-01-01 00:03:15          4   78.92
271                      1 2014-01-01 00:04:20          3   31.54

In [ ]:
## Crea el objeto EntitySet
# Un EntitySet es un contenedor que agrupa varios DataFrames relacionados entre sí, como una mini base de datos en memoria.
es = ft.EntitySet()

es = es.add_dataframe(dataframe_name="customers", dataframe=df_customers, index="customer_id")
es = es.add_dataframe(dataframe_name="products", dataframe=df_products, index="product_id")
es = es.add_dataframe(dataframe_name="transactions", dataframe=df_transactions, index="transaction_id")
es = es.add_dataframe(dataframe_name="sessions", dataframe=df_sessions, index="session_id")

es = es.add_relationship("products", "product_id", "transactions", "product_id")
es = es.add_relationship("sessions", "session_id", "transactions", "session_id")
es = es.add_relationship("customers", "customer_id", "sessions", "customer_id")

es

/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/featuretools/entityset/entityset.py:1733: UserWarning: index customer_id not found in dataframe, creating new integer column
  warnings.warn(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/featuretools/entityset/entityset.py:1733: UserWarning: index product_id not found in dataframe, creating new integer column
  warnings.warn(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/featuretools/entityset/entityset.py:1733: UserWarning: index transaction_id not found in dataframe, creating new integer column
  warnings.warn(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/featuretools/entityset/entityset.py:1733: UserWarning: index session_id not found in dataframe, creating new integer column
  warnings.warn(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/woodwork/type_sys/utils.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
/home/juanma/anaconda3/envs/dm_clase15/lib/python3.11/site-packages/featuretools/entityset/entityset.py:393: UserWarning: Logical type Categorical for child column product_id does not match parent column product_id logical type Integer. Changing child logical type to match parent.
  warnings.warn(

Entityset: None
  DataFrames:
    customers [Rows: 5, Columns: 4]
    products [Rows: 5, Columns: 2]
    transactions [Rows: 500, Columns: 5]
    sessions [Rows: 35, Columns: 4]
  Relationships:
    transactions.product_id -> products.product_id
    transactions.session_id -> sessions.session_id
    sessions.customer_id -> customers.customer_id

In [ ]:
es.plot()

ImportError: Please install graphviz to plot. (See https://featuretools.alteryx.com/en/stable/install.html#installing-graphviz for details)

feature_matrix → el DataFrame final. Una fila por cliente, una columna por feature generada. Esto es lo que le pasarías a un modelo.
feature_defs → la lista de features con su definición. Sirve para reproducir exactamente las mismas transformaciones sobre datos nuevos en producción.

In [ ]:
#feature_matrix, feature_defs = ft.dfs(entityset=es, target_dataframe_name="products")
feature_matrix, feature_defs = ft.dfs(entityset=es, target_dataframe_name="customers")
#feature_matrix, feature_defs = ft.dfs(entityset=es, target_dataframe_name="transactions")
#feature_matrix, feature_defs = ft.dfs(entityset=es, target_dataframe_name="sessions")

In [ ]:
feature_matrix

,zip_code,COUNT(sessions),MODE(sessions.device),NUM_UNIQUE(sessions.device),COUNT(transactions),MAX(transactions.amount),MEAN(transactions.amount),MIN(transactions.amount),SKEW(transactions.amount),STD(transactions.amount),...,STD(sessions.MIN(transactions.amount)),STD(sessions.SKEW(transactions.amount)),STD(sessions.SUM(transactions.amount)),SUM(sessions.MAX(transactions.amount)),SUM(sessions.MEAN(transactions.amount)),SUM(sessions.MIN(transactions.amount)),SUM(sessions.SKEW(transactions.amount)),SUM(sessions.STD(transactions.amount)),MODE(transactions.sessions.device),NUM_UNIQUE(transactions.sessions.device)
customer_id,,,,,,,,,,,,,,,,,,,,,
0,60091,0,NaN,<NA>,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.00,0.000000,0.00,0.000000,0.000000,NaN,<NA>
1,13244,8,mobile,3,119,149.15,75.148655,5.73,0.123116,45.163495,...,5.739770,0.444126,316.388722,1108.98,599.570158,85.21,0.389205,352.566101,mobile,3
2,13244,7,desktop,3,67,146.81,81.233134,5.81,-0.160628,40.371822,...,19.517969,0.483145,418.124271,830.04,486.661571,109.32,0.001909,238.898839,tablet,3
3,60091,6,desktop,3,82,148.86,82.132927,8.73,-0.060535,42.633775,...,17.521535,0.366322,236.944472,811.24,498.781825,129.60,-1.628207,237.283142,desktop,3
4,60091,8,mobile,3,123,149.95,71.882439,6.29,0.165638,42.276191,...,7.111911,0.351386,297.486182,1130.76,582.678756,98.37,1.281989,344.551882,mobile,3

In [ ]:
feature_defs

[<Feature: zip_code>,
 <Feature: COUNT(sessions)>,
 <Feature: MODE(sessions.device)>,
 <Feature: NUM_UNIQUE(sessions.device)>,
 <Feature: COUNT(transactions)>,
 <Feature: MAX(transactions.amount)>,
 <Feature: MEAN(transactions.amount)>,
 <Feature: MIN(transactions.amount)>,
 <Feature: SKEW(transactions.amount)>,
 <Feature: STD(transactions.amount)>,
 <Feature: SUM(transactions.amount)>,
 <Feature: DAY(birthday)>,
 <Feature: DAY(join_date)>,
 <Feature: MONTH(birthday)>,
 <Feature: MONTH(join_date)>,
 <Feature: WEEKDAY(birthday)>,
 <Feature: WEEKDAY(join_date)>,
 <Feature: YEAR(birthday)>,
 <Feature: YEAR(join_date)>,
 <Feature: MAX(sessions.COUNT(transactions))>,
 <Feature: MAX(sessions.MEAN(transactions.amount))>,
 <Feature: MAX(sessions.MIN(transactions.amount))>,
 <Feature: MAX(sessions.SKEW(transactions.amount))>,
 <Feature: MAX(sessions.STD(transactions.amount))>,
 <Feature: MAX(sessions.SUM(transactions.amount))>,
 <Feature: MEAN(sessions.COUNT(transactions))>,
 <Feature: MEAN(sessions.MAX(transactions.amount))>,
 <Feature: MEAN(sessions.MEAN(transactions.amount))>,
 <Feature: MEAN(sessions.MIN(transactions.amount))>,
 <Feature: MEAN(sessions.SKEW(transactions.amount))>,
 <Feature: MEAN(sessions.STD(transactions.amount))>,
 <Feature: MEAN(sessions.SUM(transactions.amount))>,
 <Feature: MIN(sessions.COUNT(transactions))>,
 <Feature: MIN(sessions.MAX(transactions.amount))>,
 <Feature: MIN(sessions.MEAN(transactions.amount))>,
 <Feature: MIN(sessions.SKEW(transactions.amount))>,
 <Feature: MIN(sessions.STD(transactions.amount))>,
 <Feature: MIN(sessions.SUM(transactions.amount))>,
 <Feature: MODE(sessions.DAY(session_start))>,
 <Feature: MODE(sessions.MONTH(session_start))>,
 <Feature: MODE(sessions.WEEKDAY(session_start))>,
 <Feature: MODE(sessions.YEAR(session_start))>,
 <Feature: NUM_UNIQUE(sessions.DAY(session_start))>,
 <Feature: NUM_UNIQUE(sessions.MONTH(session_start))>,
 <Feature: NUM_UNIQUE(sessions.WEEKDAY(session_start))>,
 <Feature: NUM_UNIQUE(sessions.YEAR(session_start))>,
 <Feature: SKEW(sessions.COUNT(transactions))>,
 <Feature: SKEW(sessions.MAX(transactions.amount))>,
 <Feature: SKEW(sessions.MEAN(transactions.amount))>,
 <Feature: SKEW(sessions.MIN(transactions.amount))>,
 <Feature: SKEW(sessions.STD(transactions.amount))>,
 <Feature: SKEW(sessions.SUM(transactions.amount))>,
 <Feature: STD(sessions.COUNT(transactions))>,
 <Feature: STD(sessions.MAX(transactions.amount))>,
 <Feature: STD(sessions.MEAN(transactions.amount))>,
 <Feature: STD(sessions.MIN(transactions.amount))>,
 <Feature: STD(sessions.SKEW(transactions.amount))>,
 <Feature: STD(sessions.SUM(transactions.amount))>,
 <Feature: SUM(sessions.MAX(transactions.amount))>,
 <Feature: SUM(sessions.MEAN(transactions.amount))>,
 <Feature: SUM(sessions.MIN(transactions.amount))>,
 <Feature: SUM(sessions.SKEW(transactions.amount))>,
 <Feature: SUM(sessions.STD(transactions.amount))>,
 <Feature: MODE(transactions.sessions.device)>,
 <Feature: NUM_UNIQUE(transactions.sessions.device)>]

In [ ]:
## Parte 2 pycaret

In [ ]:
import pycaret

In [ ]:
from pycaret import datasets
df = pycaret.datasets.get_data('insurance')

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
from pycaret.regression import RegressionExperiment
exp = pycaret.regression.RegressionExperiment()

# Inicializa el entorno en pycaret y crea el proceso de transformación para preparar los datos para el modelado y la implementación.
reg = exp.setup(data=df, target="charges")

In [ ]:
best = reg.compare_models()

In [ ]:
## Otro dataset

In [ ]:
df = pycaret.datasets.get_data("hepatitis")

,Class,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,0,30,2,1.0,2,2,2,2,1.0,2.0,2.0,2.0,2.0,2.0,1.0,85.0,18.0,4.0,NaN,1
1,0,50,1,1.0,2,1,2,2,1.0,2.0,2.0,2.0,2.0,2.0,0.9,135.0,42.0,3.5,NaN,1
2,0,78,1,2.0,2,1,2,2,2.0,2.0,2.0,2.0,2.0,2.0,0.7,96.0,32.0,4.0,NaN,1
3,0,31,1,NaN,1,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,0.7,46.0,52.0,4.0,80.0,1
4,0,34,1,2.0,2,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,200.0,4.0,NaN,1

In [ ]:
from pycaret.classification import ClassificationExperiment

exp = pycaret.classification.ClassificationExperiment()
clf = exp.setup(data=df, target="Class", imputation_type="iterative", categorical_iterative_imputer="rf", numeric_iterative_imputer="rf", iterative_imputation_iters=5)

In [ ]:
clf.X_train.head()

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
138,45,1,2.0,1,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,1.3,85.0,44.0,4.2,85.0,2
133,38,1,1.0,2,2,2,2,2.0,1.0,2.0,2.0,2.0,2.0,0.4,243.0,49.0,3.8,90.0,2
42,33,1,2.0,2,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,1.0,46.0,90.0,4.4,60.0,1
23,42,1,2.0,2,2,2,2,2.0,2.0,2.0,2.0,2.0,2.0,0.9,60.0,63.0,4.7,47.0,1
135,51,1,2.0,2,2,2,2,1.0,1.0,2.0,1.0,2.0,2.0,0.8,NaN,33.0,4.5,NaN,2

In [ ]:
best = clf.compare_models(sort='AUC')